### ISSUE TITLE
"Structure contains more than one model" Error

### ISSUE THREAD

**Issue by ariesselman** [debbiemarkslab/EVcouplings#108]
Running the pipeline, I would like to do the standard compare part of the code to get TP rates, etc, but I receive this error. 

> Traceback (most recent call last):
>   File "/groups/marks/software/anaconda/envs/evcouplings_env/lib/python3.6/site-packages/evcouplings/utils/pipeline.py", line 454, in execute_wrapped
>     outcfg = execute(**config)
>   File "/groups/marks/software/anaconda/envs/evcouplings_env/lib/python3.6/site-packages/evcouplings/utils/pipeline.py", line 174, in execute
>     outcfg = runner(**incfg)
>   File "/groups/marks/software/anaconda/envs/evcouplings_env/lib/python3.6/site-packages/evcouplings/fold/protocol.py", line 606, in run
>     return PROTOCOLS[kwargs["protocol"]](**kwargs)
>   File "/groups/marks/software/anaconda/envs/evcouplings_env/lib/python3.6/site-packages/evcouplings/fold/protocol.py", line 545, in standard
>     binary=kwargs["maxcluster"]
>   File "/groups/marks/software/anaconda/envs/evcouplings_env/lib/python3.6/site-packages/evcouplings/fold/protocol.py", line 221, in compare_models_maxcluster
>     exp_pos, exp_chain = _determine_pos(exp_file)
>   File "/groups/marks/software/anaconda/envs/evcouplings_env/lib/python3.6/site-packages/evcouplings/fold/protocol.py", line 173, in _determine_pos
>     filename
> evcouplings.utils.config.InvalidParameterError: Structure contains more than one model: output/DLG4_RAT/DLG4_RAT_1_b0.5/compare/aux/DLG4_RAT_1_b0.5_3i4w_A_143.pdb

Is this an issue with the "reduce_chains" argument? It is set to default in these runs. I would still like to get back multimer contacts in these runs.

**Comment by thomashopf** [comment]
This problem happens in the fold stage when comparing the predicted models to experimental structures (very unambiguous naming, I know...). The used tool (maxcluster) is very sensitive to things like alternative locations or multiple models (like in NMR structures), so this is a preemptive crash, which is a bit of an unnecessary harsh landing... The thing is, the structures extracted in the compare stage shouldn't have any of these issues :/

Can you please point me to the output of that job on Orchestra?

Band-aid fix if you only want the compare stage for TP rates: simpy disable fold stage in the config file, you will get the full compare output (but no structures).

If you need the comparison to experimental structures of folded models, I would limit the structures in the compare stage to a predefined set of PDB IDs that are unproblematic.

**Comment by sacdallago** [comment]
@thomashopf should we catch this and produce another type of error response? Sounds like that, to me. In case we can turn this issue into an enhancement/feature for v0.0.2/3

**Comment by thomashopf** [comment]
@ariesselman Can you please point me to the output of that job on Orchestra?

**Comment by thomashopf** [comment]
Problem was that the first_index parameter in the align section didn't make it through to the compare stage, leading to a numbering mismatch, leading to empty structures. The standard protocol, analogously to the existing protocol, now passes through first_index as an output. 

(Alternative solution is to define specify first_index in the global section, but this wouldn't work with complexes where we have two alignments).
