### ISSUE TITLE
Remove resize tool in bokeh-based mutation matrix plots

### ISSUE THREAD

**Issue by thomashopf** [debbiemarkslab/EVcouplings#109]
See #102 and https://github.com/bokeh/bokeh/issues/4196

Fix is trivial: Change https://github.com/debbiemarkslab/EVcouplings/blob/develop/evcouplings/visualize/mutations.py#L336 to `TOOLS = "hover"`, we can live without the resize.

But needs verification that it actually fixes the problem with the latest version of bokeh

**Comment by thomashopf** [comment]
Whoever gets round to changing & testing should just merge the fix to this right away

**Comment by thomashopf** [comment]
Needs fixing as soon as possible

**Comment by aggreen** [comment]
working on it now

**Comment by aggreen** [comment]
Closed - #112
