### ISSUE TITLE
Update example config files

### ISSUE THREAD

**Issue by sacdallago** [debbiemarkslab/EVcouplings#110]
One of the things to add is:

https://github.com/debbiemarkslab/EVcouplings/blob/develop/config/sample_config_monomer_o2.txt#L143

Now the options are `standard` for plmc and `mean_field` for dca.

Please comment here for any other changes to the headers in the config files

**Comment by kpgbrock** [comment]
currently in the o2 example, in compare stage the option pdb_search_method should be pdb_alignment_method according to the code, and I think it's missing in the orchestra example config files

**Comment by aggreen** [comment]
@kpgbrock apologies for this, it is fixed in #142

**Comment by sacdallago** [comment]
We can close, for now. There are gonna be other changes in ev0.3
