### ISSUE TITLE
Index mapping in non-focus mode

### ISSUE THREAD

**Issue by thomashopf** [debbiemarkslab/EVcouplings#12]
Segments and index remapping in the coupling stage do not accommodate the following case:
- Position present in the sequence alignment
- No corresponding position present in the target sequence

Since all of the pipeline currently operates in focus mode (and this is the only sensible mode for downstream stages like compare, mutate and fold), this is not an issue currently. If non-focus mode applications are ever integrated into the pipeline that require mapping to a target sequence, this issue has to be addressed.

**Comment by aggreen** [comment]
Thomas - we assigned this to you because it seems like a "note to self" because it will only become an issue if and when we go to implement non-focus mode

**Comment by thomashopf** [comment]
Probably never going to happen, so closing for now
