### ISSUE TITLE
Starting position vs region

### ISSUE THREAD

**Issue by sacdallago** [debbiemarkslab/EVcouplings#149]
I was just thinking about this with @aggreen and she couldn't give me a definite answer, so just to see if someone has an idea. It's for clarity, rather than anything else.

IF I pass a sequence via FASTA (assume a length of 200) and define a region in it (50 to 100) and also specify that the starting position of the FASTA sequence is 20 (original length of the protein 600), will the computation consider the starting of the region at 50 or 70? Is this important (I assume for alignment purposes it is?)?

Thanks!!! :)

**Comment by kpgbrock** [comment]
To answer the question - it would start at 50 when numbering from the full sequence (or the 30th residue in your input sequence file) if you specify the first_index parameter to be 20 I believe.  Or to put it more simply:

If you input a sequence file and further specify a range of that sequence to run, the current default is to consider the first residue in the file to be at position 1.  However, if you want to change the numbering - i.e. input a start and end range based on the Uniprot numbering of the full sequence as opposed to numbering based on position in your input sequence file - you can specify the "first_index" parameter.  So in this case, if you specify "first_index" to be 20, then inputting a region from 50 to 100 will give you the part of the sequence that starts with the 50th residue based on full sequence numbering, or the 30th residue in your input sequence file.
