### ISSUE TITLE
Change some flag names and entry points

### ISSUE THREAD

**Issue by sacdallago** [debbiemarkslab/EVcouplings#155]
I suggest that for `0.0.3` we change some flags both for clarity and _"seriousness"_:

1. The flag `--yolo` --> `--overwrite-previous-results` or `--overwrite-results`. More verbose: yes, more explicit: also. But especially: feels way less awkward to tell someone in another lab to use that flag when ev fails on existing results. + the `-y` option will still remain for those that prefer the short version.
2. The entry point `evcouplings_dbupdate`, either `evcouplings databases update` borrowing the idea from https://github.com/debbiemarkslab/EVcouplings/issues/117#issuecomment-360989845 or `evcouplings_databases` as it's not always an `update` operation (e.g. the first time it's a create operation) and also "db" is an obscure term for most humans.

If anyone disagrees, has other suggestions or is against this, please comment.

**Comment by aggreen** [comment]
1. I am a big fan of the yolo option name, and I think given the
seriousness of every other aspect of this package, it is ok to have one
humorous element. Plus, I think it adds character (and whenever I've told a
collaborator I've gotten a laugh). My vote is in favor of keeping it.

2. No objection to this change. I do think db is acceptable to humans who
are using command line interfaces, but I see no problem with changing it.

**Comment by thomashopf** [comment]
1. Zhe German Department of Humour and Command-Line Parameters wants to keep this ;)

2. I would turn this into a subcommand whenever the subcommands for monomer/complexes are getting implemented (e.g. evcouplings fetch_databases). Wouldn't touch it before that to avoid a double change.

**Comment by kpgbrock** [comment]
Just want to voice my support for the yolo flag too ... after all, yolo? :D

**Comment by thomashopf** [comment]
;)

**Comment by sacdallago** [comment]
Okay, okay :D soooorryyyy
