### ISSUE TITLE
Deploy to pip rising errors

### ISSUE THREAD

**Issue by sacdallago** [debbiemarkslab/EVcouplings#163]
@b-schubert @thomashopf the autodeploy to pip is still not working correctly, **but the package seems to be deployed anyway**.

Now pip authenticates correctly thanks to @b-schubert fixes ( see: https://travis-ci.org/debbiemarkslab/EVcouplings/jobs/362726271#L1224 ) but it apparently **fails** to deploy the new release (see: https://travis-ci.org/debbiemarkslab/EVcouplings/jobs/362726271#L1344 ).

Nevertheless, from the old pip: https://pypi.python.org/pypi/evcouplings/0.0.3 (although notice that the Markdown has not been processed) and on the new pip: https://pypi.org/project/evcouplings .

I don't know how to fix this 🤷‍♀️

**Comment by thomashopf** [comment]
That's because the Python 3.5 target was quicker and succesfully uploaded first, causing 3.6 to fail.

Solution: https://stackoverflow.com/questions/32892122/prevent-travis-deploying-multiple-times-when-im-running-my-tests-on-multiple-no
