### ISSUE TITLE
Application termination not detected on O2

### ISSUE THREAD

**Issue by thomashopf** [debbiemarkslab/EVcouplings#176]
See b0.2 and b0.3 runs for `/n/scratch2/105280abb7b4c88bbc1e7db8761d45e8`, both terminated by slurm because of excess memory usage, but there is no .terminated file.

Two possible reasons:
1) The current configuration terminates jobs right away with SIGKILL or the time window before SIGKILL following some other signal is too short to wind things down - in this case cannot do anything but ask RC to change the slurm config

2) slurm uses a signal that is not in the list of signals that are currently caught - but according to documentation on the web it should be SIGTERM unless there is a SIGKILL right away

Right now the pipeline catches the following signals (https://github.com/debbiemarkslab/EVcouplings/blob/develop/evcouplings/utils/pipeline.py#L451):
* SIGINT
* SIGTERM
* SIGUSR1
* SIGUSR2 (used by LSF on O1 for job termination)

**Comment by sacdallago** [comment]
I guess this would be a good addition to #166 , whenever I get around working on that..

**Comment by sacdallago** [comment]
And I'm happy that someone is using the web interface :)
