### ISSUE TITLE
o2 cron-job for dbupdate

### ISSUE THREAD

**Issue by sacdallago** [debbiemarkslab/EVcouplings#179]
Just putting this as an issue, so we can follow up on it.

@b-schubert have you had time to look into this?

**Comment by thomashopf** [comment]
SIFTS tables should ideally be on a weekly schedule (as opposed to monthly updates for sequence databases)

**Comment by sacdallago** [comment]
REF https://github.com/debbiemarkslab/EVcouplings/issues/189#issuecomment-431940186

**Comment by thomashopf** [comment]
Updated.
