### ISSUE TITLE
Missing required param `pseudo_count`

### ISSUE THREAD

**Issue by sacdallago** [debbiemarkslab/EVcouplings#190]
(Note to self)

in `/n/groups/marks/web/backend/runs` check:
- `5f61e22c929cd14d1383f3e42fc2fac7/5f61e22c929cd14d1383f3e42fc2fac7_b0.2.failed`
- `21c3094ae7c1995a67029ef52e794f41/21c3094ae7c1995a67029ef52e794f41_e10.failed`

There seems to be a missing param as a dependency of another setting in the options of the job sumission: figure out what and amend in the backend.

**Comment by sacdallago** [comment]
While trying to solve this, I realized that there is **no documentation** about using `mean_field` as a protocol in the couplings stage at the level of the example config: https://github.com/debbiemarkslab/EVcouplings/blob/develop/config/sample_config_monomer.txt#L143

So, things to do:
- [ ] Add documentation about using `mean_field` in the couplings stage. Especially required parameters that would otherwise generate errors, like the above

Question to all (@thomashopf @b-schubert @aggreen ) is who is best suited to do that? Aka: who has implemented this part and knowledge about it?

**Comment by aggreen** [comment]
The person who implemented it is Sophia Mersmann but I can update the
config file, no problem. Since it's only adding two lines of documentation
and not changing any code, I'm going to be naughty and do it directly on
develop.

**Comment by sacdallago** [comment]
Thanks Anna!

**Comment by aggreen** [comment]
Fixed by most recent commit

**Comment by sacdallago** [comment]
Ok, adding this param fixed the missing param error, but now it seems like the pipeline itself is broken-ish? Opening a new issue
