### ISSUE TITLE
Add 'checkpoint_domtbl' option to alignment stage

### ISSUE THREAD

**Issue by nrollins-Ag** [debbiemarkslab/EVcouplings#219]
Currently there is no option to save the .domtbl files generated during alignment stage. Alongside the checkpoint_ali option, would be useful for checking the integrity of the alignment process

**Comment by thomashopf** [comment]
Yes would be very useful but unfortunately I am not aware of a jackhmmer command line flag that would allow to do this (unlike --chkali for alignment and --chkhmm HMM). 

The only way to get a domtbl after each iteration would be to manually create a jackhmmer-like protocol using phmmer + hmmsearch and saving the output after each stage, but that means creating a new protocol and quite a bit of work... so closing for now but whenever someone embarks on that mission please feel free to reopen.
