### ISSUE TITLE
compare stage: search using HMM from alignment stage

### ISSUE THREAD

**Issue by thomashopf** [debbiemarkslab/EVcouplings#22]
Current implementation uses jackhmmer only against the sequences of PDB structures. For greater sensitivity, should search with the broader HMM profile generated by searching against Uniref/Uniprot.

To implement,
1) generate HMM file from .a2 alignment (better to use than checkpoints_hmm parameter of jackhmmer search) using hmmbuild
2) scan HMM against PDB Uniprot sequence database (from SIFTS object) using hmmsearch

**Comment by b-schubert** [comment]
See #66

**Comment by aggreen** [comment]
See #86

**Comment by aggreen** [comment]
fixed by #113
