### ISSUE TITLE
Monomer v. Complex FOLD step output comparisons

### ISSUE THREAD

**Issue by cross12tamu** [debbiemarkslab/EVcouplings#233]
Howdy!

I have the full pipeline running now for various monomer and complex runs (see #230) after figuring out the full paths issue. Now I have, what I think is an easy question (hopefully) for y'all.

**_context:_**
> I run the monomer pipeline. No errors that exit the script. Output files in `FOLD` have a `psipred` directory and it contains: `*.pdb` files, `...CouplingScores...clashes.csv`, `*.in/outcfg`, and a few others (likely what is expected).

> I run the complex piepline. Little, or no errors (eg: a `RuntimeWarning: invalid value encountered in .. Max Ent calc`),  however the error, nor any of the others, halt the pipeline. Now, when I check the `FOLD` directory, the results are different. I get the `HADDOCK` restraint `*.tbl` files, the `*.in/outcfg`; and that's it. 

**QUESTION** 
From a complete complex pipeline run, are .tbl files for HADDOCK-based docking the expected final output? If so, what is your recommended work process for mapping those onto a predicted structure? Do you use monomer fold output in conjunction with `.tbl` files on the HADDOCK web server?

@jrr-cpt

**Comment by thomashopf** [comment]
Hi @cross12tamu, 

Yes this is the expected output for the complex pipeline - we haven't directly integrated any of the docking tools yet. The easiest solution should be to dock using the HADDOCK web server, I seem to remember that setting HADDOCK up locally is a bit tricky.

(By the way the other messages are just warnings, not errors, and are safe to ignore)

**Comment by cross12tamu** [comment]
👍 (little tardy, but understood)
