### ISSUE TITLE
Erroneously escaped dollar signs in sbatch --wrap string 

### ISSUE THREAD

**Issue by GodloveD** [debbiemarkslab/EVcouplings#242]
This error is observed under slurm 19.05.6

When I execute this command produces the following string that is passed to `sbatch --wrap` :
```
$ evcouplings -p RASH_HUMAN -P /data/${USER}/ev_out_files -b "0.3,0.5,0.7" sample_config_monomer.txt
```
```
export PATH=/a/new/path/bin:$PATH \&\& evcouplings_runcfg /data/apptest3/ev_out_files_b0.3_config.txt \&\& evcouplings_summarize protein_monomer /data/apptest3/ev_out_files /data/apptest3/ev_out_files_b0.3_config.txt /data/apptest3/ev_out_files_b0.5_config.txt /data/apptest3/ev_out_files_b0.7_config.txt
```
Note in the escaped dollar signs (i.e. `\$\$`).  Because these dollar signs are escaped they are treated as strings passed to `sbatch --wrap` and are not recognized as linking multiple commands on a single line.  If I manually create the same submission script and remove the backslash characters the job seems to run as intended.

**Comment by thomashopf** [comment]
Independent of the escaping - can you please detail what your expectation here would be regarding the substitution of ${USER} (and who would substitute? bash? slurm?)? 

There is no substitution mechanism inside evcouplings - the wrapper application will treat this as a literal relative or absolute path prefix for making folder and prefixing output file names, not performing any substitutions (and I probably want to keep it that way for simplicity).

The way this is intended to be used is that the submitting user fully specifies the prefix:
1) either as a prefix relative to the current working directory (this is my preferred usage)
2) as an absolute prefix 

e.g. for two runs of RASH_HUMAN with different parameters
* -P rash_runs/RASH_trial_run_1
* -P rash_runs/RASH_trial_run_2

In both cases, the prefix has to be unique for the job - the way you specified the prefix in your command, all jobs for the same user would start overwriting each other.

**Comment by GodloveD** [comment]
Hi @thomashopf.  This command was executed in bash, so variable expansion is going to happen properly at the command line and the correct value for `${USER}` will already be supplied by the time the `evcouplings` process has a chance to parse options and arguments.  (_In all honesty though, I think I may have just used a literal when I did the actual command and then substituted the env var when I created the report to anonymize._  😄) 

Looking forward to hearing what you have to say about the escaped dollar signs.  I think that different versions of slurm may differ in their behavior regarding strings passed with `--wrap` so that might have something to do with the error.  Thanks!

**Comment by thomashopf** [comment]
@GodloveD Upon rereading your issue, I think you mean escaped ampersands, not escaped dollar signs, right? I.e. the `\&\&` linking the command chain passed into sbatch --wrap.

To be honest, at the moment I don't understand how the escape characters could be appearing, as we do not explicitly escape the commands... 

The individual commands are assembled here:
https://github.com/debbiemarkslab/EVcouplings/blob/80d30b3d2568ae3327f973346be73cdcd41f678b/evcouplings/utils/app.py#L376

Then the submission is handled by this function (using subclassing for the different type of cluster engines):
https://github.com/debbiemarkslab/EVcouplings/blob/80d30b3d2568ae3327f973346be73cdcd41f678b/evcouplings/utils/batch.py#L398

The following slurm submission command is created by substitution into
```
"sbatch --job-name={name} {dependent} {resources} --wrap 'srun {cmd}'"
```

through the following piece of Python:
```python
        combine = " && " if command.environment else ""
        cmd = " && ".join(command.environment) + combine + " && ".join(command.command)
        resources = self._prepare_resources(command.resources)
        submit = self.submit_command.format(
            cmd=cmd,
            resources=resources,
            dependent=dep,
            name=command.command_id
        )
```

**Comment by GodloveD** [comment]
Yes I mean escaped ampersands.  Don't know what I was thinking.  😄

**Comment by thomashopf** [comment]
Hehe okay good we sorted that out. 

How did you exactly retrieve the escaped command above, is that an output from some slurm monitor command? 

I think the first check would be to check the value of the *submit* variable right before the cluster submitter is called https://github.com/debbiemarkslab/EVcouplings/blob/80d30b3d2568ae3327f973346be73cdcd41f678b/evcouplings/utils/batch.py#L404 

I suppose the easiest way to test that in your environment would be adding a ```print(submit)``` after line 409 to your copy (easiest to do by using ```pip install -e <package source directory> ```)

If the command still looks good there, it can only be the call to subprocess.Popen() or something about slurm.

**Comment by GodloveD** [comment]
Thanks @thomashopf.  I placed the `print` command in the script as you suggested and I can verify that the escape sequences are inserted at the logging stage.  So it's a non-issue.  I'm still struggling trying to get the command that you gave me in #240 to run.  Trying to determine which errors might be do to our setup or might be a product of containerization.  I'll close this since it's a non-issue.
