### ISSUE TITLE
Make 'create evzoom' optional in config- crashes pipeline for non-AA alphabets

### ISSUE THREAD

**Issue by nrollins-Ag** [debbiemarkslab/EVcouplings#244]
Right now, alphabets not including all amino acid characters crash during couplings stage- when trying to generate EVzoom visualization. This means other folders (especially compare and mutate) directories aren't created.

For now, an easy fix is to make EVzoom optional so that we can avoid the crash and still output those results.

**Comment by thomashopf** [comment]
@nrollins-Ag This issue has been already been fixed (although not yet merged, as mentioned in the respective issues, cf. #237 #196) by https://github.com/debbiemarkslab/EVcouplings/commit/fc0301bcbbaa898f4d7e5262524d471f8d5c4a2c.

Is the fix not working, or are you still on an older version of the package? Unless you have a problem with the fix (please let me know exact error then), I will merge into develop today.

**Comment by thomashopf** [comment]
@nrollins-Ag Did you have a chance to try the fix already?

**Comment by thomashopf** [comment]
Now on develop branch, closing this, please let me know if issue comes up again
