### ISSUE TITLE
Wrong error message in CouplingsModel.delta_hamiltonian 

### ISSUE THREAD

**Issue by nikkithadani** [debbiemarkslab/EVcouplings#259]
https://github.com/debbiemarkslab/EVcouplings/blob/86fbd62f04851800b8716b8798155e71088149a2/evcouplings/couplings/model.py#L699-L702

I think in line 702 `self.target_seq[i]` should be `self.target_seq[pos[i]]`

**Comment by thomashopf** [comment]
Thanks @nikkithadani
