### ISSUE TITLE
Code for running jackhmmer to produce MSA, and postprocess to get A2M.file

### ISSUE THREAD

**Issue by lzhangUT** [debbiemarkslab/EVcouplings#270]
Hi, 
I am interested in the code of how to use jackhmmer for MSA and the postprocess to produce .A2M.file. I searched in the github but couldn't find it. can you point it to somehow?
Thanks 

ps: I think I found the code for postproccess of jackhmmer outputfiles (such as stockholm, a3m files, evcouplings/align/alignment.py), but still didn't find the code for how you used jackhmmer for MSA. I kinda know how to do it online but would like to see the code of how you use  it. Thanks.

never mind, I think I found it.

**Comment by shrrr** [comment]
Hi, I also have the same problem with you @lzhangUT , can you show an example of using jackhmmer？
