### ISSUE TITLE
Incompatible .model file from EVCouplings web server

### ISSUE THREAD

**Issue by jsunn-y** [debbiemarkslab/EVcouplings#273]
I have generated an MSA for a tryptophan synthase B subunit variant using the EVcouplings web server. Unfortunately, after importing with `from evcouplings.couplings import CouplingsModel` and then loading the model with `c = CouplingsModel("tm9D8_2.model")`, I get the following error:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_20180/1939998030.py in <module>
----> 1 c = CouplingsModel("tm9D8_2.model")

~/miniconda3/envs/mlde2/lib/python3.7/site-packages/evcouplings/couplings/model.py in __init__(self, model_file, precision, file_format, **kwargs)
    269             else:
    270                 with open(model_file, "rb") as f:
--> 271                     self.__read_plmc_v2(f, precision)
    272         elif file_format == "plmc_v1":
    273             if is_file_obj:

~/miniconda3/envs/mlde2/lib/python3.7/site-packages/evcouplings/couplings/model.py in __read_plmc_v2(self, f, precision)
    377                 self.f_ij[i, j], = np.fromfile(
    378                     f, dtype=(precision, (self.num_symbols, self.num_symbols)),
--> 379                     count=1
    380                 )
    381                 self.f_ij[j, i] = self.f_ij[i, j].T

ValueError: not enough values to unpack (expected 1, got 0)
```
I have uploaded the sequences from the alignment (.a2m) and the .model file [here](https://drive.google.com/drive/u/0/folders/1B3Q0qkFIPWO2FHvi6Rbt3uMbu76-aJoY) for your reference.

**Comment by thomashopf** [comment]
Hi @jsunn-y, before we look into this, could you please also point us to the corresponding web server run where you downloaded the model file (v1 or v2, job id, or link)? Thanks!

**Comment by jsunn-y** [comment]
Thanks! Here is the job link: https://v2.evcouplings.org/results/0c2d9dcc43864858bd22ea64a2be3de0

**Comment by thomashopf** [comment]
Thank you, I can reproduce the error. It looks like this is a problem with the download of the model file through the server (it should have 125 MB in total), which we have had issues before. I will look into this further but will take some time.

If you urgently need this model file, can you please write an email to support@evcouplings.org with a link to the job from above? Then someone from the lab can share the model file with you through Dropbox or the like.

**Comment by jsunn-y** [comment]
Sounds good, thank you!
