### ISSUE TITLE
Troubleshooting Help 

### ISSUE THREAD

**Issue by JodC58972** [debbiemarkslab/EVcouplings#279]
Im getting this error when I run my config file. I checked and the Uniprot ID's are in the fast file I'm using but I am still getting this error. 

`evcouplings.utils.BailoutException: align: No sequences found`

I have downloaded the recommended python packages as well as jackhmmer and plmc. I am using the complex pipeline. I have a region of [50,100] for one of my proteins. I am running this locally and changed all required sections as outlined in the run file. 

Has anyone else experienced this problem? If so what can be done to fix it. 

Thanks

**Comment by thomashopf** [comment]
Hi @JodC58972, is this issue still relevant our can we close it as resolved due to your interaction with our support email address?

**Comment by thomashopf** [comment]
Assuming fixed, please reopen if necessary
