### ISSUE TITLE
ResourceError: issue while running EVcouplings

### ISSUE THREAD

**Issue by bshrestha0** [debbiemarkslab/EVcouplings#288]
Hi, 

I am trying to run EVcouplings using a custom sequence file as a database and getting this error:  "ResourceError: Invalid status code (405) for URL: https://www.uniprot.org/mapping/". I think the error might be at the SIFTS mapping step. I don't have the sifts_mapping_table and sifts_sequence_db, so I created a directory without any files in it.  The run completed the align and couplings steps but failed at the compare step. I also tried with downloading uniprot sequences and using the fasta file as a database but I am still getting the same error. I installed latest version of EVcouplings using pip and  the other dependencies either with using conda or manually as suggested in the README.md file. I have included the commands used to run the job, error message, the config file and the input sequence.

Thank you!
 
**Commands to run job**

`from evcouplings.utils import read_config_file
from evcouplings.utils.pipeline import execute

config = read_config_file("test_config_monomer.txt")
outcfg = execute(**config)`

**Config file:**
[test_config_monomer.txt](https://github.com/debbiemarkslab/EVcouplings/files/11104039/test_config_monomer.txt)

**Input sequence**
[SMOELLENDORFFII_test.txt](https://github.com/debbiemarkslab/EVcouplings/files/11104050/SMOELLENDORFFII_test.txt)

**Error:**
 /Users/bikash/miniforge3/envs/EV/lib/python3.8/site-packages/sklearn/base.py:432: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
      warnings.warn(
    /Users/bikash/miniforge3/envs/EV/lib/python3.8/site-packages/sklearn/base.py:432: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
      warnings.warn(
    /Users/bikash/miniforge3/envs/EV/lib/python3.8/site-packages/evcouplings/couplings/pairs.py:125: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
      stacked_ecs = top_ecs.append(flipped)
    /Users/bikash/miniforge3/envs/EV/lib/python3.8/site-packages/evcouplings/couplings/pairs.py:129: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
      stacked_ecs.groupby(["i", "A_i"]).sum()
    /Users/bikash/miniforge3/envs/EV/lib/python3.8/site-packages/evcouplings/visualize/parameters.py:137: RuntimeWarning: divide by zero encountered in log2
      B = -fi * np.log2(fi)
    /Users/bikash/miniforge3/envs/EV/lib/python3.8/site-packages/evcouplings/visualize/parameters.py:137: RuntimeWarning: invalid value encountered in multiply
      B = -fi * np.log2(fi)

    ---------------------------------------------------------------------------

    ResourceError                             Traceback (most recent call last)

    Cell In[15], line 8
          5 from evcouplings.utils.pipeline import execute
          7 config = read_config_file("test_config_monomer.txt")
    ----> 8 outcfg = execute(**config)

    File ~/miniforge3/envs/EV/lib/python3.8/site-packages/evcouplings/utils/pipeline.py:187, in execute(**config)
        184 write_config_file(stage_incfg, incfg)
        186 # run stage
    --> 187 outcfg = runner(**incfg)
        189 # prefix output keys if this parameter is
        190 # given in stage configuration, to avoid
        191 # name clashes if same protocol run multiple times
        192 if key_prefix is not None:

    File ~/miniforge3/envs/EV/lib/python3.8/site-packages/evcouplings/compare/protocol.py:1250, in run(**kwargs)
       1242 if kwargs["protocol"] not in PROTOCOLS:
       1243     raise InvalidParameterError(
       1244         "Invalid protocol selection: " +
       1245         "{}. Valid protocols are: {}".format(
       1246             kwargs["protocol"], ", ".join(PROTOCOLS.keys())
       1247         )
       1248     )
    -> 1250 return PROTOCOLS[kwargs["protocol"]](**kwargs)

    File ~/miniforge3/envs/EV/lib/python3.8/site-packages/evcouplings/compare/protocol.py:653, in standard(**kwargs)
        650 create_prefix_folders(aux_prefix)
        652 # Step 1: Identify 3D structures for comparison
    --> 653 sifts_map, sifts_map_full = _identify_structures(**{
        654     **kwargs,
        655     "prefix": aux_prefix,
        656 })
        658 # save selected PDB hits
        659 sifts_map.hits.to_csv(
        660     outcfg["pdb_structure_hits_file"], index=True
        661 )

    File ~/miniforge3/envs/EV/lib/python3.8/site-packages/evcouplings/compare/protocol.py:152, in _identify_structures(**kwargs)
        137 check_required(
        138     kwargs,
        139     [
       (...)
        149     ]
        150 )
        151 # get SIFTS mapping object/sequence DB
    --> 152 s = SIFTS(
        153     kwargs["sifts_mapping_table"],
        154     kwargs["sifts_sequence_db"]
        155 )
        157 reduce_chains = not kwargs["compare_multimer"]
        159 # determine if we need to find structures
        160 # by sequence search or just fetching
        161 # based on Uniprot/PDB identifier

    File ~/miniforge3/envs/EV/lib/python3.8/site-packages/evcouplings/compare/sifts.py:284, in SIFTS.__init__(self, sifts_table_file, sequence_file)
        282 # if path for sequence file given, but not there, create
        283 if sequence_file is not None and not valid_file(sequence_file):
    --> 284     self.create_sequence_file(sequence_file)
        286 # add Uniprot ID column if we have sequence mapping
        287 # from FASTA file
        288 if self.sequence_file is not None:

    File ~/miniforge3/envs/EV/lib/python3.8/site-packages/evcouplings/compare/sifts.py:448, in SIFTS.create_sequence_file(self, output_file, chunk_size, max_retries)
        446 while True:
        447     try:
    --> 448         seqs = fetch_uniprot_mapping(ch)
        449         break
        450     except requests.ConnectionError as e:
        451         # count as failed try

    File ~/miniforge3/envs/EV/lib/python3.8/site-packages/evcouplings/compare/sifts.py:105, in fetch_uniprot_mapping(ids, from_, to, format)
        102 r = requests.post(url, data=params)
        104 if r.status_code != requests.codes.ok:
    --> 105     raise ResourceError(
        106         "Invalid status code ({}) for URL: {}".format(
        107             r.status_code, url
        108         )
        109     )
        111 return r.text

    ResourceError: Invalid status code (405) for URL: https://www.uniprot.org/mapping/

**Comment by thomashopf** [comment]
This is due to an API change at Uniprot, please upgrade to the latest version of EVcouplings on the develop branch to work around this. Full release on pypi will follow.
