### ISSUE TITLE
Fix numpy str deprecations

### ISSUE THREAD

**Issue by thomashopf** [debbiemarkslab/EVcouplings#291]
in sequences_to_matrix
    matrix = np.empty((N, L), dtype=np.str)
AttributeError: module 'numpy' has no attribute 'str'.
`np.str` was a deprecated alias for the builtin `str`. To avoid this error in existing code, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

**Comment by charlesxu90** [comment]
Met with a same issue. Any solutions?
