### ISSUE TITLE
The 'sklearn' PyPI package is deprecated, use 'scikit-learn' error

### ISSUE THREAD

**Issue by fbalo-medium** [debbiemarkslab/EVcouplings#296]
I sometimes get this error when installing evcouplings via pip.

**Comment by ChristophKnapp** [comment]
I have the same problem. Allthough its not sometimes for me. 

Seems to me we need to dumb down the python version until sklearn is not deprecated anymore or sklearn imports need to be replaced with scikit-learn. I would prefer the later. 

Is it better to install the development version?

**Comment by ChristophKnapp** [comment]
The development version installs without problems for me.

**Comment by thomashopf** [comment]
Yes, please use the development branch for now while we are in the process of preparing a new public release. You may need to use an older version of numpy and pandas if there are any error messages.

**Comment by zachcp** [comment]
+1 for updating to newer numpy and updated release.  Are there tasks you could use help on?

**Comment by fbalo-medium** [comment]
For who might need this; I was able to downgrade the packages below to this versions for the development branch to work for me.

pip install pandas==1.2.4 seaborn==0.11.2 scipy==1.7.1 numba==0.53.1 matplotlib==3.4.1 numpy==1.19.5

**Comment by joelmeyerson** [comment]
@thomashopf Is there still a new public release in the works?

**Comment by thomashopf** [comment]
Yes - the v0.2 branch is a good step closer to the new release ... I should be able to finalize this in the next weeks hopefully

**Comment by thomashopf** [comment]
The latest develop branch version should fix the sklearn/scikit-learn issue - and if it behaves stably during testing for a few weeks, it will become v0.2 eventually. 

Note this also should fix the numpy/pandas versions by replacing all deprecated function calls. If you catch any others running the most recent version, please reopen the issue.
