### ISSUE TITLE
"load()" has been removed, use yaml

### ISSUE THREAD

**Issue by fbalo-medium** [debbiemarkslab/EVcouplings#303]
Getting this error on any new run now on python 3.8 >
I think this majorly has to do with latest update from ruamel.yaml to version 0.18.5.

**Comment by joelmeyerson** [comment]
You can use `ruamel.yaml==0.17.*` as a short-term fix.

**Comment by thomashopf** [comment]
Pinned the ruamel.yaml version in setup.py in the latest develop branch version
