### ISSUE TITLE
PDB no longer provides MMTF files

### ISSUE THREAD

**Issue by pedrobfer** [debbiemarkslab/EVcouplings#307]
In trying to run the EVcouplings pipeline, I couldn't download the MMTF files needed. Then I found the following message from RCSB:

"As of July 2, 2024, RCSB PDB will no longer serve PDB data in the MMTF compression format. Users are strongly encouraged to switch to accessing the data files offered in the [compressed BinaryCIF (BCIF) format.](https://www.rcsb.org/docs/programmatic-access/file-download-services#pdb-entry-files)"

I don't have the expertise to suggest changes, but wanted to keep this record in case anyone finds the same issue.

**Comment by thomashopf** [comment]
Well that is rather unfortunate 😬 

The fix will be to swap out the MMTF loading+transformation in the PDB class to load binary CIF files and turn that into our internal dataframe-based structure https://github.com/debbiemarkslab/EVcouplings/blob/af27842c5fc72c291831261c9a19849a3e313efd/evcouplings/compare/pdb.py#L403

Hope to work on this in the next weeks as top priority on this repository - any PRs highly welcome!

Thanks a lot for the notice @pedrobfer!

**Comment by thomashopf** [comment]
I started to work on a fix, tapping into BioPythons bCIF parser

**Comment by thomashopf** [comment]
Basic bCIF integration is done (c2a766d), remaining integration with pipeline still to be tested (e.g. model number defaults need to be changed from 0 to 1)

**Comment by thomashopf** [comment]
I released a fix on the develop branch - please have a look and let me know if this works in your hands. 

Please note this depends on biopython >= 1.84, so please upgrade that accordingly. 

Keeping the issue open for now to track any other questions around the MMTF->bCIF change.

**Comment by pedrobfer** [comment]
> I released a fix on the develop branch - please have a look and let me know if this works in your hands.
> 
> Please note this depends on biopython >= 1.84, so please upgrade that accordingly.
> 
> Keeping the issue open for now to track any other questions around the MMTF->bCIF change.

It worked perfectly! Thank you very much for the quick work on this!

**Comment by thomashopf** [comment]
Fix is now also in the latest version on PyPI (v0.2.1) via `pip install evcouplings`
