### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by ChristophKnapp** [debbiemarkslab/EVcouplings#309]
Hello, I'm just getting started with evcouplings. When Itry to install the package I get the following error.

Collecting sklearn (from evcouplings)
  Using cached sklearn-0.0.post12.tar.gz (2.6 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
      rather than 'sklearn' for pip commands.
      
      Here is how to fix this error in the main use cases:
      - use 'pip install scikit-learn' rather than 'pip install sklearn'
      - replace 'sklearn' by 'scikit-learn' in your pip requirements files
        (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
      - if the 'sklearn' package is used by one of your dependencies,
        it would be great if you take some time to track which package uses
        'sklearn' instead of 'scikit-learn' and report it to their issue tracker
      - as a last resort, set the environment variable
        SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error
      
      More information is available at
      https://github.com/scikit-learn/sklearn-pypi-package
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip

The package sklearn is deprecated for a while now. I'm trying this on python 3.12.

Regards

**Comment by thomashopf** [comment]
Is this with pip install evcouplings or with the latest develop branch? If it is the former, please install from develop branch for time being

**Comment by ChristophKnapp** [comment]
pip install evcouplings

**Comment by ChristophKnapp** [comment]
That works fine. 

Thank you

**Comment by thomashopf** [comment]
The latest version that is on PyPI (v.0.2.1) now also has this issue fixed.
