### ISSUE TITLE
build_test_and_push github action fails, preventing new release

### ISSUE THREAD

**Issue by thomashopf** [debbiemarkslab/EVcouplings#314]
Run fails here: https://github.com/debbiemarkslab/EVcouplings/blob/88978eeefd9520c7c48fecb15d5a5879704d1d58/.github/workflows/build_test_and_push.yml#L34

with the following error message:

> usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
>    or: setup.py --help [cmd1 cmd2 ...]
>    or: setup.py --help-commands
>    or: setup.py cmd --help
> 
> error: invalid command 'bdist_wheel'

Problematic line was added in this commit: https://github.com/debbiemarkslab/EVcouplings/commit/55ccdf5af7eadd0d085f17d3c5e20a0bb00900a8

Strangely enough, according to the install log, the environment has `wheel-0.44.0 `

@zachcp Could you comment why this was added? Can we simply remove it again?

**Comment by thomashopf** [comment]
While updating, should also remove the Python version matrix from this action or it most likely will try to push to PyPI twice

**Comment by zachcp** [comment]
Hi @thomashopf 

Yes, please remove this if it doesn't work as intended on the main branch.  My main effort in that series of pull requests was to update the CI system and the python dependencies to allow building on a newer python/numpy/etc.  I'm glad to see it merged and if that line is interfering with the building please remove. 

Thanks again for your great work.
zach cp

zach cp

**Comment by zachcp** [comment]
FYI: here is the [full PR](https://github.com/debbiemarkslab/EVcouplings/pull/301/files).  I had  toyed with the CI to get tests to run and pass.  The bdist component is unneccesarry if it's handled elsewhere.

**Comment by thomashopf** [comment]
Hi @zachcp, thank you very much for the very quick response, much appreciated! Removing the bdist line fixes that issue.

**Comment by thomashopf** [comment]
Now failing trying to upload to test PyPI:

> ERROR    HTTPError: 400 Bad Request from https://test.pypi.org/legacy/          
>          Bad Request

**Comment by thomashopf** [comment]
Fixed by moving to pyproject.toml (retiring legacy setup.py) and using hatch to build
