### ISSUE TITLE
Clean up couplings/protocol.py

### ISSUE THREAD

**Issue by thomashopf** [debbiemarkslab/EVcouplings#57]
Currently the protocols have quite some code duplication. I already refactored some of it in the complexes_dev branch (standard and complexes protocols). After these changes are merged into master, we should continue to refactor such that mean-field protocol also gets de-duplicated.

**Comment by thomashopf** [comment]
Partly refactored protocols are now part of master branch, could now refactor the mean-field protocol

**Comment by b-schubert** [comment]
See PR #92

**Comment by b-schubert** [comment]
Resolved in PR #92
