### ISSUE TITLE
Statistics summary csv doesn't always contain all the runs

### ISSUE THREAD

**Issue by deboramarks** [debbiemarkslab/EVcouplings#71]
see marks/projects/murj_ecoli/MURJ_ECOLI  for example

**Comment by thomashopf** [comment]
This looks like the subjob crashing fatally - there is not even LSF output in the stdout.log file. Generally, if the job is shut down, there is nothing the pipeline can do about it (the only exception is that the pipeline does register it is being killed).

Any other cases where there is missing output in the summary, but the job *didn't* crash or get terminated?
