### ISSUE TITLE
Increase test coverage

### ISSUE THREAD

**Issue by thomashopf** [debbiemarkslab/EVcouplings#75]
Highest priority would be tests that check the sanity of the individual pipeline stage outputs, and that the pipeline runs through from start to end for the major workflows (monomers / complexes).

**Comment by aggreen** [comment]
Idea is we will all be writing test for the functions we have written

**Comment by sacdallago** [comment]
Testing hackathon:

- Monday 12th Feb

@b-schubert you available?

**Comment by b-schubert** [comment]
jup

On Tue, Jan 23, 2018 at 4:24 PM, Christian Dallago <notifications@github.com

**Comment by sacdallago** [comment]
I think we are good on this one. We should just always make sure that major PRs come with tests from now on
