### ISSUE TITLE
Dependencies licences

### ISSUE THREAD

**Issue by sacdallago** [debbiemarkslab/EVcouplings#83]
### Check licenses for tools and report here
As from #74

For this purpose, I propose listing all external dependencies here and slowly commenting with their licenses.

Dependencies:
- [x] CNS
- [x] psipred

**Comment by sacdallago** [comment]
# PSIPRED
http://bioinfadmin.cs.ucl.ac.uk/downloads/psipred/LICENSE

----
PLEASE READ THE FOLLOWING LICENSE AGREEMENT. BY USING THE PROGRAM YOU ARE
ACKNOWLEDGING THE FACT THAT YOU AGREE TO THE TERMS OUTLINED IN THIS
AGREEMENT. USERS WISHING TO USE THE SOFTWARE FOR COMMERCIAL ACTIVITIES
NOT COVERED BY THIS AGREEMENT SHOULD SEND E-MAIL TO: dtj@cs.ucl.ac.uk

* NOTE RECENT CHANGES TO PARAGRAPH 8 *



 PSIPRED3 - PROTEIN SECONDARY STRUCTURE PREDICTION PROGRAM BY D.T.JONES GENERAL LICENSE & CONFIDENTIALITY AGREEMENT



In regard to the protein structure prediction program (PSIPRED3)
herewith (the Software) the copyright and other intellectual property
rights to which belong to the Author(s).

Any user (the User) of the program undertakes to the Copyright holder that he
or she shall be bound by the following terms and conditions:-

1. The User will receive the Software and any related documentation in
confidence and will not use the same except for the purpose of their own 
research. The Software will be used only by such of the User's officers or
employees to whom it must reasonably be communicated to enable them to
undertake their research and who agree to be bound by the same confidence.
The User shall procure and enforce such agreement from his or her staff for
the benefit of the Copyright holder.

2. The publication of research using the Software must include an
appropriate citation to the method:

Jones, D.T. (1999) Protein secondary structure prediction based on
position-specific scoring matrices. J. Mol. Biol. 292:195-202.

3. All forms of the Software will be kept in a reasonably secure place to
prevent unauthorised access.

4. Each copy of the Software or, if not practicable then, any package
associated therewith shall be suitably marked (and such marking maintained) 
with the following copyright notice: "Copyright 2000 D.T.Jones. All Rights
Reserved.".

5. The Software may be modified, but any changes made shall be communicated
to the Author(s) and made freely available.

6. The Software may not be sold as a standalone package, or incorporated into
a commercial software package without the written permission of the Copyright
holder. The Software may be used freely for individual academic or commercial
research. The Software may also be made freely available for training or
teaching purposes.

7. The results produced by the Software may not be incorporated into any
data banks or databases which are subject to the payment of access or
license fees without the written permission of the Copyright holder.

8. The Software may be made available to users over a local network or
wide area network (including the Internet), but only if access is granted
free of charge to all authorised users. Incorporation of the Software into
a commercial Web site or other fee paying service is not allowed without
the written permission of the Copyright holder. If PSIPRED results are
returned to the user via such a network service, then a suitable
acknowledgement of the PSIPRED method must be returned somewhere in the
output text.

9. The confidentiality obligation in paragraph one shall not apply:

   (i)  to information and data known to the User at the time of
	receipt hereunder (as evidenced by its written records);

  (ii)	to information and data which was at the time of receipt in the 
	public domain or thereafter becomes so through no wrongful act of
	the User;

 (iii)	to information and data which the User receives from a third
	party not in breach of any obligation of confidentiality owed to
	the Author(s).

10. The User understands that the Software is supplied "as is". No warranty
   as to its fitness or suitability for any purpose whatsoever is made or
   implied. In no event shall the Author(s) or Copyright holder be held
   responsible for any direct or indirect damages arising through the use
   of the Software.

**Comment by thomashopf** [comment]
With CNS I think it would be the simplest solution if Debbie and Chris ask Axel Brunger if it would be okay to include it in the container

**Comment by sacdallago** [comment]
# CNS
http://cns-online.org/v1.21/ (license button on bottom right)
----


             LICENSE FOR ACADEMIC (NON-PROFIT) INSTITUTIONS
                    TO USE CNSSOLVE GENERAL-RELEASE 1.2

                         TERMS OF AGREEMENT

BY DOWNLOADING OR USING THE CRYSTALLOGRAPHY & NMR SYSTEM SOLVE (CNSSOLVE)
GENERAL-RELEASE 1.2 SOFTWARE YOU AGREE TO THE FOLLOWING TERMS:

- YALE UNIVERSITY RETAINS OWNERSHIP OF ALL MATERIALS (INCLUDING
  SOFTWARE AND DOCUMENTATION). REPORTS OF MODIFICATIONS OR DERIVATIVE
  WORKS ARE TO BE MADE TO YALE UNIVERSITY, AND ARE TO BE MADE AVAILABLE
  ON REQUEST.

- YOU SHALL NOT USE THE SOFTWARE FOR ANY PURPOSE (RESEARCH OR
  OTHERWISE) THAT IS SUPPORTED BY A "FOR PROFIT" ORGANIZATION WITHOUT
  PRIOR WRITTEN AUTHORIZATION.

- YOU SHALL NOT DISCLOSE IN ANY FORM EITHER THE DELIVERED SOFTWARE OR
  DOCUMENTATION OR ANY MODIFICATIONS OR DERIVATIVE WORKS BASED ON THE
  SOFTWARE OR DOCUMENTATION TO THIRD PARTIES WITHOUT PRIOR WRITTEN
  AUTHORIZATION.

- IF YOU RECEIVE A REQUEST TO FURNISH ALL OR ANY PORTION OF THE
  SOFTWARE TO ANY THIRD PARTY, YOU WILL NOT FULFILL SUCH A REQUEST AND
  WILL REFER IT IN WRITING TO YALE UNIVERSITY.

- YOU AGREE THAT THE SOFTWARE IS FURNISHED ON AN "AS IS" BASIS AND
  THAT YALE UNIVERSITY IN NO WAY WARRANTS THE SOFTWARE OR ANY OF ITS
  RESULTS AND IS IN NO WAY LIABLE FOR ANY USE YOU MAKE OF THE SOFTWARE.
  EXCEPT AS OTHERWISE PROVIDED IN THIS SECTION, YALE UNIVERSITY
  DISCLAIMS ALL WARRANTIES, REPRESENTATIONS, AND STATEMENTS, EXPRESS
  OR IMPLIED, STATUTORY OR OTHERWISE, INCLUDING, WITHOUT LIMITATION, ANY
  IMPLIED WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR
  PURPOSE. IN NO EVENT SHALL YALE UNIVERSITY BE LIABLE FOR ANY ACTUAL,
  DIRECT, INDIRECT, SPECIAL, CONSEQUENTIAL, OR INCIDENTAL DAMAGES,
  HOWEVER CAUSED, INCLUDING, WITHOUT LIMITATION, ANY DAMAGES ARISING OUT
  OF THE USE OR OPERATION OF THE SOFTWARE, LOSS OF USE OF THE SOFTWARE,
  OR DAMAGE OF ANY SORT TO THE USER.

- YOU AGREE THAT ANY REPORTS OR PUBLICATION OF RESULTS OBTAINED WITH
  THE SOFTWARE WILL ACKNOWLEDGE ITS USE BY CITATION OF THE FOLLOWING
  ARTICLE:

    "CRYSTALLOGRAPHY AND NMR SYSTEM (CNS): A NEW SOFTWARE SYSTEM
    FOR MACROMOLECULAR STRUCTURE DETERMINATION". BRUNGER A.T., ADAMS P.D.,
    CLORE G.M., DELANO W.L., GROS P., GROSSE-KUNSTLEVE R.W., JIANG J.-S.,
    KUSZEWSKI J., NILGES N., PANNU N.S., READ R.J., RICE L.M., SIMONSON T.,
    AND WARREN G.L. ACTA CRYST. D54, 905-921 (1998).

**Comment by sacdallago** [comment]
Bottom line: both can be used for non-commercial purposes (so, we are good to go) but we should cite them in the Readme (which we do, if I'm not mistaken).

Please let me know if there are other licenses to be checked ( pinging @kpgbrock && @b-schubert )

**Comment by thomashopf** [comment]
> YOU SHALL NOT DISCLOSE IN ANY FORM EITHER THE DELIVERED SOFTWARE OR
> DOCUMENTATION OR ANY MODIFICATIONS OR DERIVATIVE WORKS BASED ON THE
> SOFTWARE OR DOCUMENTATION TO THIRD PARTIES WITHOUT PRIOR WRITTEN
> AUTHORIZATION.

This is the much bigger problem - hence why I suggested Debbie and Chris reach out to them

**Comment by sacdallago** [comment]
I'll ping them

**Comment by sacdallago** [comment]
Update: this discussion is only relevant if the dependencies are shipped with the package itself, so for now we won't do that. In terms of docker container, we can make a container which expects the dependencies on a certain volume (e.g. a path on the local computer, or container-to-container volumes sharing, but the container with the dependencies will be maintained by whoever needs it, whereas the container for evcouplings will build on this repo)
