### ISSUE TITLE
Additional last step in pipeline: store list of files to database

### ISSUE THREAD

**Issue by sacdallago** [debbiemarkslab/EVcouplings#84]
After the pipeline has finished generating all files, there should be a final optional step where files are copied from the FS to a database. This should be as transparent as possible (i.e.: database can be mongo/postgres/...) and the files to be stored are read from some config file.

**Comment by sacdallago** [comment]
To be implemented in management stage of pipeline?

**Comment by thomashopf** [comment]
1) Configuration which output items to store should be in management section of configuration file, just like the list of keys that go in the archive file

2) I would add the files to the database as the pipeline goes through the stages (this is inside utils/pipeline.py) to allow the website to progressively update the results

3) Some of the pipeline outputs are large for database standards (e.g. model file, or potentially the alignment) 

4) Best to keep this as simple as possible and support one sensible choice (my feeling is MongoDB or the like is the way to go here - I wouldn't bother storing blobs in a relational database)

5) Implementing this shouldn't impair the current status update function (which is not only for the webserver but also for keeping track of large amounts of batch jobs)

**Comment by sacdallago** [comment]
Update: we probably have to write different "drivers" for this, but currently I want to keep the dependencies of the backend to a minimum, and we already depend on too many things: relational db, redis, workers,... Adding another dependency (mongo) seems a bit too much. We can store blobs in relational dbs too, and as far as all text files are concerned (most of the files), those are excellent candidates to just be stored as plain TEXT or even using pandas to read them in and spit them out to an appropriate table.

When the time comes... Shouldn't be to far ahead.

**Comment by thomashopf** [comment]
I don't see any issues here. One additionally specifies the type of database (with another item in the management section, then:
* if relational database, just track status as it is now (not used for webserver anymore, but useful in other settings like tracking large number of command-line pipeline runs)
* if MongoDB, track status and additionally store the requested output keys / files (all information for webserver backend, eliminating the relational database for the webserver)

I wouldn't put the pipeline output in a relational database.

**Comment by sacdallago** [comment]
I understand. Fair enough.

Writing the abstraction layer between relational and mongo is low priority for now and I don't expect to get around doing that before end of April. So, let's keep this one for then.
