### ISSUE TITLE
parse error in uniref100_current.fasta

### ISSUE THREAD

**Issue by rohanmaddamsetti** [debbiemarkslab/EVcouplings#88]
Hi guys,

the pipeline dies almost immediately when I set off a run. I get the following parse error:

Error: Parse failed (sequence file
/groups/marks/databases/jackhmmer/uniref100/uniref100_current.fasta):
Line 1: unexpected char ; expected FASTA to start with >

I looked at this briefly with Christian, and he suggested that this is caused by some kind of encoding error (I see weird characters when I run 'head uniref100_current.fasta' on the command-line).

Thanks!
Rohan

**Comment by b-schubert** [comment]
the cron job, which is responsible of the monthly update, might have bugged out and corrupted the DBs.
could you run which in uniref100_current.fasta and report the result?

In the meantime, I can run the update script manually, which should fix the problem.

**Comment by deboramarks** [comment]
What’s your config ?

**Comment by rohanmaddamsetti** [comment]
sorry, stupid bug report. I updated my config file to the one on github and problem went away.

**Comment by rohanmaddamsetti** [comment]
wait--never mind!

job just died again with the same error. Just attached my config file.

[J-alns-paper.conf.txt](https://github.com/debbiemarkslab/EVcouplings/files/1476842/J-alns-paper.conf.txt)

**Comment by b-schubert** [comment]
the file from this months update was not fully downloaded and is corrupted. Im currently manually downloading the DBs but that will take a bit. Ill write you an email once the DBs are updated ;-)

**Comment by rohanmaddamsetti** [comment]
Thanks Benni!

**Comment by b-schubert** [comment]
Uniprot is gzipping the pasta dumps twice  now since October.....and that is causing the problem ....

**Comment by sacdallago** [comment]
@b-schubert .... mmmmmhhh pasta dumps... I'm already getting hungry

**Comment by b-schubert** [comment]
Resolved in PR #89

**Comment by cokeyk** [comment]
I also received the same problem, how did you solved the problem? 
（I utilized the esl-sfetch function to processed the fasta database and obtain the format ssi files）

**Comment by sacdallago** [comment]
@cokeyk if you used `pip install evcouplings` to install the pipeline, you have unfortunately fallen into one of the recent braking changes of uniprot's database delivery. We fixed this issue in the development branch of our pipeline and will be shipping an updated package (installable via pip) by the end of the month (sorry about that!). In the meantime, you have two alternatives:
1. Rename the `uni*.fasta` files to `uni*.fasta.gz`, and then unpack these
2. Download the development branch of this repo, `cd` into the repo's root and `pip install .` to install the development version of evcouplings with all the latest changes. Then let the `evcouplings_dbupdate` script run again and this time the `.fasta` files will be in `utf8` format.
