### ISSUE TITLE
Incorporate new coloring of EC enrichment

### ISSUE THREAD

**Issue by aggreen** [debbiemarkslab/EVcouplings#90]
New function for coloring EC enrichment should be incorporated into pipeline. The new function has more bins and a nicer color scheme.

**Comment by aggreen** [comment]
@thomashopf I have a function ready to go that would replace the existing enrichment_pymol_script function. Is there any reason to keep the old color scheme around, or should we just replace the function entirely? (Maybe keep the function as enrichment_pymol_script_legacy but don't call it in the pipeline?)

**Comment by thomashopf** [comment]
Yep let's have the new & nice one as default when calling enrichment_pymol_script, i.e. also in the pipeline, and the old one can still be obtained using legacy_style=True as parameter to the enrichment_pymol_script function (but no need to have that in config file, if someone wants the old version, they need to call the function themselves)
