### ISSUE TITLE
Feature request: visualize ECs on a one-dimensional string

### ISSUE THREAD

**Issue by rohanmaddamsetti** [debbiemarkslab/EVcouplings#97]
It would be nice if we can make figures that visualize ECs as arcs between points on a string, especially for proteins where we get some high-confidence ECs but not enough to fold the full protein.

**Comment by aggreen** [comment]
As described, this is a duplicate of #20

**Comment by sacdallago** [comment]
I'm closing as duplicate. Thanks for the catch @aggreen
