### ISSUE TITLE
Add in Uniprot and PDB id to contact maps

### ISSUE THREAD

**Issue by kpgbrock** [debbiemarkslab/EVcouplings#99]
Might be nice to add in PDB ids and uniprot id that was used to generate contact maps directly in the pdf files

**Comment by thomashopf** [comment]
Yep would be a nice addition (user should be able to decide if they want it on or off). Implementation needs attention to cases where there are many structures so text is correctly rendered on the plot (line wrapping etc.) or list is truncated after some reasonable maximum of structures to be listed.

**Comment by sacdallago** [comment]
Should this go into v0.0.2?

**Comment by thomashopf** [comment]
If it is ready by then absolutely, but not a must-have feature for v0.0.2.

**Comment by sacdallago** [comment]
Who can we assign this to?

**Comment by thomashopf** [comment]
PDB IDs and structural coverage now printed/plotted on contact maps by default
